router1[0]=A
router1[1]=B
router1[image]="miguelleitao/frr-isep"
router1[bridged]=true

router2[0]=B
router2[1]=C
router2[image]="miguelleitao/frr-isep"

router3[0]=C
router3[1]=A
router3[image]="miguelleitao/frr-isep"
