#!/bin/sh
EBTABLES=ebtables
CHAIN=FORWARD
usage() {
  echo "# $1v0.91"
  echo "Usage: $1 node1 node2 [up|down] ";
  exit
}
link_down() {
  ${EBTABLES} -D ${CHAIN} -i $1 -o $2
  ${EBTABLES} -D ${CHAIN} -i $2 -o $1
}
link_up() {
  ${EBTABLES} -A ${CHAIN} -i $1 -o $2 -j ACCEPT
  ${EBTABLES} -A ${CHAIN} -i $2 -o $1 -j ACCEPT
}
link_show() {
  ${EBTABLES} -L ${CHAIN} -i $1 -o $2 
  ${EBTABLES} -L ${CHAIN} -i $2 -o $1 
}

echo "$#"
if [ $# = 3 ]; then
	echo $3
	case "$3" in
		"down")
			link_down $1 $2
			;;
		"up")
			link_up $1 $2
			;;
		*)
			usage $0
			;;
	esac
	exit
fi
if [ $# = 2 ]; then
	link_show $1 $2
	exit
fi
usage $0

